# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Edit settings
language: zh-Hans
timezone: Asia/Shanghai

# Site settings
title: Honghzh
email: honghz29@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  可能包含了日常知识小记和一些前端、Python、各种Tools的个人实践(爬坑)指南。有可能是超认真教程，也有可能是有点杂乱的随笔，写作十分随心
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://honghzh.github.io" # the base hostname & protocol for your site

social_sharing: false
github_username:  honghzh
google_analytic_id:
disqus_name:

permalink: /:categories/:title
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num'
  title: ':title - page :num'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
  tags:
    title: 'Posts tagged with :tag'
  collections:
    title: 'Posts in collection :coll'

# jekyll seo tag settings
logo: assets/images/example-image.png
twitter:
  username: 

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..3
  auto_id_stripping: true
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archives